### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/Vue-ToDo#1]
As per now the UI doesn't look promising. Workarounds have to be made in the following:-

- Make the two components differentiable from each other.
- Use proper Vuetify components for each UI widget.
- Align the list-items properly so that all of them lie in the same line irrespective of their length.

**Comment by JoelLau** [comment]
hey, if anyone isn't already, can I work on this?

**Comment by jamesgeorge007** [comment]
@JoelLau Go ahead :+1:
