### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/Vue-ToDo#2]
As per now the Docs contain only what's necessary for the contributors. 
It has to be supplemented with useful information regarding ```state management``` and how ```vuex``` simplifes the process.

**Comment by fzd370** [comment]
Can I work on this?

**Comment by jamesgeorge007** [comment]
@fzd370 Sure, Go on :+1:

**Comment by jamesgeorge007** [comment]
@fzd370 What's the status?
