### ISSUE TITLE
Extended capabilities

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/Vue-ToDo#3]
As of now, only adding and removing tasks are possible. It has to be extended with the ability to move a task to the ```in-progress``` and when completed to the ```done``` stage.

**Comment by susantruong** [comment]
@jamesgeorge007 I am new with Git and GitHub. However, I want to try on this issue. If you don't mind, would you please assign it to me?

**Comment by jamesgeorge007** [comment]
@susantruong No worries, Go ahead :+1: 
Just let me know if you're facing any sort of trouble :smile:

**Comment by jamesgeorge007** [comment]
@susantruong Haven't heard from you for a while?
